#!/bin/sh
SQL_SCRIPT_DIR="$(cd "$(pwd)" && cd ../sql && pwd)"

echo "================================== Getting all user data in empty table ======================================"
psql --file "${SQL_SCRIPT_DIR}/empty-user-data.sql" --host localhost --port 5432 --username postgres --dbname userdb
curl --request GET http://localhost:8080/user-service/api/v0/users | jq .

echo "================================== Getting all user data in filled table ======================================"
psql --file "${SQL_SCRIPT_DIR}/add-user-data.sql" --host localhost --port 5432 --username postgres --dbname userdb
curl --request GET http://localhost:8080/user-service/api/v0/users | jq .

echo "=================================================== END ======================================================="